/**
 * Database access layer. All data is stored in PostgreSQL.
 * Requires DATABASE_URL. No local/JSON fallback.
 */
// Re-export all public API from pgLocalDb (getDb removed with JSON backend)
export {
  getProviderConnections,
  getProviderConnectionById,
  createProviderConnection,
  updateProviderConnection,
  deleteProviderConnection,
  reorderProviderConnections,
  deleteProviderConnectionsByProvider,
  getProviderNodes,
  getProviderNodeById,
  createProviderNode,
  updateProviderNode,
  deleteProviderNode,
  getModelAliases,
  setModelAlias,
  deleteModelAlias,
  getMitmAlias,
  setMitmAliasAll,
  getCombos,
  getComboById,
  getComboByName,
  createCombo,
  updateCombo,
  deleteCombo,
  getApiKeys,
  getApiKeyById,
  createApiKey,
  updateApiKey,
  deleteApiKey,
  validateApiKey,
  cleanupProviderConnections,
  getUsers,
  getUserById,
  getUserByOAuth,
  getUserByEmail,
  getOrCreateUserByOAuth,
  createUserWithPassword,
  getOrCreateUserByEmail,
  updateUser,
  deleteUser,
  getSettings,
  updateSettings,
  exportDb,
  importDb,
  isCloudEnabled,
  getCloudUrl,
  getPricing,
  getPricingForModel,
  updatePricing,
  resetPricing,
  resetAllPricing,
} from "@/lib/db/pgLocalDb.js";
