// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings, updateSettings, isCloudEnabled, getCloudUrl,
  getProviderConnections, getProviderConnectionById,
  createProviderConnection, updateProviderConnection,
  deleteProviderConnection, deleteProviderConnectionsByProvider,
  reorderProviderConnections, cleanupProviderConnections,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool,
  getApiKeys, getApiKeyById, getApiKeyByValue, getApiKeyUsageSummaries, createApiKey, updateApiKey, deleteApiKey, validateApiKey,
  getApiKeyGroups, getApiKeyGroupById, getDefaultApiKeyGroup,
  createApiKeyGroup, updateApiKeyGroup, deleteApiKeyGroup, setDefaultApiKeyGroup, DEFAULT_API_KEY_GROUP_ID,
  getCombos, getComboById, getComboByName,
  createCombo, updateCombo, deleteCombo, deleteCombosByIds,
  DEFAULT_COMBO_LIST_ID,
  getComboLists, getComboListById, createComboList, renameComboList, deleteComboList,
  reorderComboLists, moveCombosToList,
  getModelAliases, setModelAlias, deleteModelAlias,
  getModelMappings, setModelMappings, deleteModelMapping,
  getCustomModels, addCustomModel, deleteCustomModel,
  getMitmAlias, setMitmAliasAll,
  getPricing, getPricingForModel, updatePricing, resetPricing, resetAllPricing,
  getPricingModels, upsertPricingModels, deletePricingModel,
  getPricingMappings, setPricingMappings, replacePricingMappings, deletePricingMapping,
  exportDb, importDb,
} from "@/lib/db/index.js";
