"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Badge, Button, Card, CardSkeleton } from "@/shared/components";
import { useCopyToClipboard } from "@/shared/hooks/useCopyToClipboard";

const AUTO_CLASS_TOKENS = [
  { token: "auto::normal", label: "Normal", description: "General-purpose LLM requests." },
  { token: "auto::thinking", label: "Thinking", description: "Requests with explicit reasoning intent." },
  { token: "auto::code", label: "Code", description: "Code-focused requests selected by C.6.4." },
  { token: "auto::vision", label: "Vision", description: "Requests that require visual input support." },
  { token: "auto::image", label: "Image", description: "Image-generation routing class." },
  { token: "auto::video", label: "Video", description: "Video-generation routing class." },
];

function formatTimestamp(value) {
  if (!value) return "Not available";
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? String(value) : parsed.toLocaleString();
}

function formatLatency(value) {
  const latency = Number(value);
  return Number.isFinite(latency) && latency >= 0 ? `${Math.round(latency)} ms` : "Unknown";
}

function healthCounts(members) {
  return (members || []).reduce(
    (counts, member) => {
      const status = String(member?.health?.status || "unknown").toLowerCase();

      if (status === "healthy") {
        counts.healthy += 1;
      } else {
        counts.unknown += 1;
      }

      return counts;
    },
    { healthy: 0, unknown: 0 }
  );
}

export default function AutoRoutingPage() {
  const [snapshot, setSnapshot] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");
  const { copied, copy } = useCopyToClipboard(1800);

  const loadSnapshot = useCallback(async (force = false) => {
    try {
      const response = await fetch("/api/combos/auto", {
        method: force ? "POST" : "GET",
        headers: force ? { "Content-Type": "application/json" } : undefined,
        body: force
          ? JSON.stringify({
              forceInventoryRefresh: true,
              includeDynamic: true,
            })
          : undefined,
        cache: "no-store",
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(
          data.error ||
          "Failed to load automatic routing candidates"
        );
      }

      setSnapshot(data);

    } catch (loadError) {
      setError(
        loadError?.message ||
        "Failed to load automatic routing candidates"
      );

    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    let active = true;

    fetch("/api/combos/auto", {
      cache: "no-store",
    })
      .then(async (response) => {
        const data = await response.json();

        if (!response.ok) {
          throw new Error(
            data.error ||
            "Failed to load automatic routing candidates"
          );
        }

        return data;
      })
      .then((data) => {
        if (active) {
          setSnapshot(data);
        }
      })
      .catch((loadError) => {
        if (active) {
          setError(
            loadError?.message ||
            "Failed to load automatic routing candidates"
          );
        }
      })
      .finally(() => {
        if (active) {
          setLoading(false);
        }
      });

    return () => {
      active = false;
    };
  }, []);

  const combosById = useMemo(() => {
    return new Map(
      (snapshot?.combos || []).map(
        (combo) => [
          combo.id,
          combo,
        ]
      )
    );
  }, [snapshot]);

  const totalCandidates = useMemo(() => {
    return (snapshot?.combos || []).reduce(
      (total, combo) =>
        total +
        Number(
          combo?.candidateCount ||
          0
        ),
      0
    );
  }, [snapshot]);

  if (loading) {
    return (
      <div className="flex flex-col gap-6">
        <CardSkeleton />
        <CardSkeleton />
      </div>
    );
  }

  return (
    <div className="flex min-w-0 flex-col gap-6 px-1 sm:px-0">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-xl font-semibold text-text-main">
            Auto Routing
          </h2>
          <p className="mt-1 text-sm text-text-muted">
            Virtual candidate pools generated by C.6.3 and consumed by the C.6.4 automatic routing engine.
          </p>
        </div>

        <Button
          icon="refresh"
          variant="secondary"
          loading={refreshing}
          onClick={() => {
            setRefreshing(true);
            setError("");
            loadSnapshot(true);
          }}
        >
          Refresh
        </Button>
      </div>

      {error && (
        <Card>
          <div className="flex items-center gap-3 text-red-500">
            <span className="material-symbols-outlined">
              error
            </span>
            <span className="text-sm">
              {error}
            </span>
          </div>
        </Card>
      )}

      <div className="grid gap-4 md:grid-cols-3">
        <Card
          title="Generic Token"
          icon="route"
        >
          <div className="flex items-center justify-between gap-3 rounded-[10px] bg-surface-2 p-3">
            <code className="min-w-0 truncate text-sm font-semibold text-primary">
              auto::auto
            </code>

            <Button
              size="sm"
              variant="ghost"
              icon={
                copied === "auto::auto"
                  ? "check"
                  : "content_copy"
              }
              onClick={() =>
                copy(
                  "auto::auto",
                  "auto::auto"
                )
              }
            >
              {copied === "auto::auto"
                ? "Copied"
                : "Copy"}
            </Button>
          </div>

          <p className="mt-3 text-xs text-text-muted">
            Request intent is classified by the backend. The UI does not select a class or candidate.
          </p>
        </Card>

        <Card
          title="Inventory Source"
          icon="database"
        >
          <p className="text-2xl font-semibold text-text-main">
            {snapshot?.sourceInventoryModelCount ?? 0}
          </p>
          <p className="mt-1 text-xs text-text-muted">
            Active inventory models
          </p>
          <p className="mt-3 text-xs text-text-muted">
            Refreshed{" "}
            {formatTimestamp(
              snapshot?.sourceInventoryRefreshedAt
            )}
          </p>
        </Card>

        <Card
          title="Generated Candidates"
          icon="account_tree"
        >
          <p className="text-2xl font-semibold text-text-main">
            {totalCandidates}
          </p>
          <p className="mt-1 text-xs text-text-muted">
            Across six explicit auto classes
          </p>

          <div className="mt-3 flex flex-wrap gap-2">
            <Badge variant="primary">
              Virtual
            </Badge>
            <Badge variant="default">
              Derived
            </Badge>
            <Badge variant="default">
              Non-persistent
            </Badge>
          </div>
        </Card>
      </div>

      <div className="grid gap-4 xl:grid-cols-2">
        {AUTO_CLASS_TOKENS.map((entry) => {
          const combo =
            combosById.get(
              entry.token
            );

          const members =
            combo?.members || [];

          const counts =
            healthCounts(
              members
            );

          return (
            <Card
              key={entry.token}
              title={
                combo?.name ||
                `Auto ${entry.label}`
              }
              subtitle={entry.description}
              icon="hub"
              action={
                <Button
                  size="sm"
                  variant="ghost"
                  icon={
                    copied === entry.token
                      ? "check"
                      : "content_copy"
                  }
                  onClick={() =>
                    copy(
                      entry.token,
                      entry.token
                    )
                  }
                >
                  {copied === entry.token
                    ? "Copied"
                    : "Copy"}
                </Button>
              }
            >
              <div className="mb-4 flex flex-wrap items-center gap-2">
                <code className="rounded bg-surface-2 px-2 py-1 text-xs font-semibold text-primary">
                  {entry.token}
                </code>

                <Badge variant="success">
                  Healthy {counts.healthy}
                </Badge>

                <Badge variant="default">
                  Unknown {counts.unknown}
                </Badge>

                <Badge variant="primary">
                  Candidates{" "}
                  {combo?.candidateCount ?? 0}
                </Badge>
              </div>

              <div className="mb-3 flex flex-wrap gap-2 text-[11px] text-text-muted">
                <span>
                  virtual=
                  {String(
                    combo?.virtual ??
                    true
                  )}
                </span>
                <span>
                  derived=
                  {String(
                    combo?.derived ??
                    true
                  )}
                </span>
                <span>
                  persisted=
                  {String(
                    combo?.persisted ??
                    false
                  )}
                </span>
              </div>

              {members.length === 0 ? (
                <div className="rounded-[10px] border border-border-subtle bg-bg p-4 text-sm text-text-muted">
                  No currently eligible candidates for this class.
                </div>

              ) : (
                <div className="max-h-80 overflow-y-auto rounded-[10px] border border-border-subtle bg-bg px-3">
                  {members.map(
                    (member) => (
                      <div
                        key={
                          member.canonicalId ||
                          member.model
                        }
                        className="flex flex-col gap-2 border-b border-border-subtle py-3 last:border-b-0 sm:flex-row sm:items-center sm:justify-between"
                      >
                        <div className="min-w-0">
                          <p className="truncate text-sm font-medium text-text-main">
                            {member.model}
                          </p>
                          <p className="truncate text-[11px] text-text-muted">
                            {member.canonicalId}
                          </p>
                        </div>

                        <div className="flex shrink-0 items-center gap-2">
                          <Badge
                            variant={
                              member
                                ?.health
                                ?.status ===
                              "healthy"
                                ? "success"
                                : "default"
                            }
                            size="sm"
                          >
                            {member
                              ?.health
                              ?.status ||
                              "unknown"}
                          </Badge>

                          <span className="text-xs text-text-muted">
                            {formatLatency(
                              member
                                ?.health
                                ?.latencyMs
                            )}
                          </span>
                        </div>
                      </div>
                    )
                  )}
                </div>
              )}
            </Card>
          );
        })}
      </div>
    </div>
  );
}
