import { CLAUDE_API_HEADERS } from "../shared.js";

export default {
  id: "kimi",
  priority: 170,
  hasFree: true,
  alias: "kimi",
  aliases: ["kimi-coding", "kmc"],
  display: {
    name: "Kimi",
    icon: "psychology",
    color: "#1E3A8A",
    textIcon: "KM",
    website: "https://platform.moonshot.cn",
    notice: {
      text: "Free tier: ¥15 (~$2) + $5 coupon trial (~¥35 total). 3 RPM free. Auto-discovered via modelsFetcher.",
      apiKeyUrl: "https://platform.moonshot.cn/console/api-keys",
      signupUrl: "https://www.kimi.com/code",
    },
  },
  category: "freeTier",
  authModes: ["oauth", "apikey"],
  hasOAuth: true,
  transport: {
    baseUrl: "https://api.moonshot.cn/v1/chat/completions",
    headers: {},
  },
  transports: [
    {
      format: "openai",
      baseUrl: "https://api.moonshot.cn/v1/chat/completions",
      auth: { combined: true, header: "Authorization", scheme: "bearer", hooks: ["kimiHeaders"] },
    },
    {
      format: "openai",
      baseUrl: "https://api.moonshot.ai/v1/chat/completions",
      auth: { combined: true, header: "Authorization", scheme: "bearer", hooks: ["kimiHeaders"] },
    },
    {
      format: "claude",
      baseUrl: "https://api.kimi.com/coding/v1/messages",
      urlSuffix: "?beta=true",
      headers: { ...CLAUDE_API_HEADERS },
      auth: { combined: true, header: "x-api-key", scheme: "raw", hooks: ["kimiHeaders"] },
    },
  ],
  models: [
    { id: "kimi-k3", name: "Kimi K3", free: true },
    { id: "k3", name: "Kimi K3 (Code)", free: true },
    { id: "kimi-for-coding", name: "Kimi for Coding", free: true },
    { id: "kimi-for-coding-highspeed", name: "Kimi for Coding Highspeed", free: true },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code", free: true },
    { id: "kimi-k2.7-code-highspeed", name: "Kimi K2.7 Code Highspeed", free: true },
    { id: "kimi-k2.6", name: "Kimi K2.6", free: true },
    { id: "kimi-k2.5", name: "Kimi K2.5", free: true },
    { id: "kimi-k2.5-thinking", name: "Kimi K2.5 Thinking", free: true },
    { id: "kimi-latest", name: "Kimi Latest", free: true },
    { id: "moonshot-v1-8k", name: "Moonshot V1 8K", free: true },
    { id: "moonshot-v1-32k", name: "Moonshot V1 32K", free: true },
    { id: "moonshot-v1-128k", name: "Moonshot V1 128K", free: true },
  ],
  modelsFetcher: { url: "https://api.moonshot.cn/v1/models", type: "openai" },
  passthroughModels: true,
  serviceKinds: ["llm", "webSearch"],
  searchViaChat: {
    defaultModel: "kimi-k3",
    endpoint: "https://api.moonshot.cn/v1/chat/completions",
    pricingUrl: "https://platform.kimi.ai/docs/pricing/chat",
  },
  oauth: {
    clientId: "17e5f671-d194-4dfb-9706-5516cb48c098",
    deviceCodeUrl: "https://auth.kimi.com/api/oauth/device_authorization",
    tokenUrl: "https://auth.kimi.com/api/oauth/token",
    refreshUrl: "https://auth.kimi.com/api/oauth/token",
    refreshLeadMs: 300000,
    authorizeDeviceUrl: "https://www.kimi.com/code/authorize_device",
  },
  features: { usage: true, usageApikey: true },
};
