import { CLAUDE_API_HEADERS } from "../shared.js";

export default {
  id: "minimax",
  priority: 90,
  hasFree: true,
  alias: "minimax",
  display: {
    name: "MiniMax",
    icon: "memory",
    color: "#7C3AED",
    textIcon: "MM",
    website: "https://platform.minimax.io",
    notice: {
      text: "Free trial credits on signup (phone verification, promo-dependent). Also via OpenRouter :free. Auto-discovered via modelsFetcher.",
      apiKeyUrl: "https://platform.minimax.io/user-center/basic-information/interface-key",
    },
  },
  category: "freeTier",
  hasFree: true,
  transport: {
    baseUrl: "https://api.minimax.io/v1/chat/completions",
    validateUrl: "https://api.minimax.io/v1/models",
    headers: {},
  },
  transports: [
    {
      format: "openai",
      baseUrl: "https://api.minimax.io/v1/chat/completions",
      auth: { combined: true, header: "Authorization", scheme: "bearer" },
    },
    {
      format: "claude",
      baseUrl: "https://api.minimax.io/anthropic/v1/messages",
      urlSuffix: "?beta=true",
      headers: { ...CLAUDE_API_HEADERS },
      auth: { combined: true, header: "x-api-key", scheme: "raw" },
    },
  ],
  models: [
    { id: "MiniMax-M3", name: "MiniMax M3", targetFormat: "claude", free: true },
    { id: "MiniMax-M2.7", name: "MiniMax M2.7", free: true },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5", free: true },
    { id: "MiniMax-M2.1", name: "MiniMax M2.1", free: true },
    { id: "minimax-m3", name: "MiniMax M3 (lowercase)", free: true },
    { id: "minimax-m2.7", name: "MiniMax M2.7 (lowercase)", free: true },
    { id: "minimax-image-01", name: "MiniMax Image 01", params: ["n","size","response_format"], kind: "image" },
    { id: "speech-2.8-hd", name: "Speech 2.8 HD", kind: "tts" },
    { id: "speech-2.8-turbo", name: "Speech 2.8 Turbo", kind: "tts" },
    { id: "speech-2.6-hd", name: "Speech 2.6 HD", kind: "tts" },
    { id: "speech-2.6-turbo", name: "Speech 2.6 Turbo", kind: "tts" },
    { id: "speech-02-hd", name: "Speech 02 HD", kind: "tts" },
    { id: "speech-02-turbo", name: "Speech 02 Turbo", kind: "tts" },
    { id: "speech-01-hd", name: "Speech 01 HD", kind: "tts" },
    { id: "speech-01-turbo", name: "Speech 01 Turbo", kind: "tts" },
  ],
  modelsFetcher: { url: "https://api.minimax.io/v1/models", type: "openai" },
  passthroughModels: true,
  serviceKinds: ["llm","image","imageToText","webSearch","tts"],
  ttsConfig: { baseUrl: "https://api.minimax.io/v1/t2a_v2", authType: "apikey", authHeader: "bearer", format: "minimax-tts" },
  imageConfig: { baseUrl: "https://api.minimaxi.com/v1/images/generations" },
  searchViaChat: {
    defaultModel: "MiniMax-M2.7",
    endpoint: "https://api.minimaxi.com/v1/text/chatcompletion_v2",
    pricingUrl: "https://www.minimaxi.com/document/price",
  },
  features: { usage: true, usageApikey: true },
};
