export default {
  id: "opencode-go",
  priority: 210,
  alias: "opencode-go",
  aliases: [
    "ocg",
  ],
  uiAlias: "ocg",
  display: {
    name: "OpenCode Go",
    icon: "terminal",
    color: "#E87040",
    textIcon: "OC",
    website: "https://opencode.ai/auth",
    notice: {
      text: "OpenCode Go subscription: $5/mo (then  0/mo). Access to Kimi, GLM, Qwen, MiMo, MiniMax models.",
      apiKeyUrl: "https://opencode.ai/auth",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://opencode.ai/zen/go/v1/chat/completions",
    headers: {},
  },
  // OpenCode Go assigns a fixed API dialect to each model. `transportFormat`
  // below is authoritative; the request is translated from the client format.
  transports: [
    { format: "openai", baseUrl: "https://opencode.ai/zen/go/v1/chat/completions", auth: { combined: true, header: "Authorization", scheme: "bearer" } },
    { format: "claude", baseUrl: "https://opencode.ai/zen/go/v1/messages", auth: { combined: true, header: "x-api-key", scheme: "raw", anthropicVersion: true } },
    { format: "openai-responses", baseUrl: "https://opencode.ai/zen/go/v1/responses", auth: { combined: true, header: "Authorization", scheme: "bearer" } },
  ],
  models: [
    { id: "grok-4.5", name: "Grok 4.5", targetFormat: "openai-responses", transportFormat: "openai-responses" },
    { id: "gpt-5.6-luna", name: "GPT 5.6 Luna", targetFormat: "openai-responses", transportFormat: "openai-responses" },
    { id: "muse-spark-1.1", name: "Muse Spark 1.1", targetFormat: "openai-responses", transportFormat: "openai-responses" },
    { id: "glm-5.3", name: "GLM 5.3", targetFormat: "openai", transportFormat: "openai" },
    { id: "glm-5.2", name: "GLM 5.2", targetFormat: "openai", transportFormat: "openai" },
    { id: "glm-5.1", name: "GLM 5.1", targetFormat: "openai", transportFormat: "openai" },
    { id: "kimi-k3", name: "Kimi K3", targetFormat: "openai", transportFormat: "openai" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code", targetFormat: "openai", transportFormat: "openai" },
    { id: "kimi-k2.6", name: "Kimi K2.6", targetFormat: "openai", transportFormat: "openai" },
    { id: "longcat-2.0", name: "LongCat 2.0", targetFormat: "openai", transportFormat: "openai" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", targetFormat: "openai", transportFormat: "openai" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", targetFormat: "openai", transportFormat: "openai" },
    { id: "deepseek-v4.1-vision", name: "DeepSeek V4.1 Vision", targetFormat: "openai", transportFormat: "openai" },
    { id: "mimo-v2.5", name: "MiMo V2.5", targetFormat: "openai", transportFormat: "openai" },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro", targetFormat: "openai", transportFormat: "openai" },
    { id: "hy3", name: "HY3", targetFormat: "openai", transportFormat: "openai" },
    { id: "ox", name: "OX", targetFormat: "openai", transportFormat: "openai" },
    { id: "minimax-m3", name: "MiniMax M3", targetFormat: "claude", transportFormat: "claude" },
    { id: "minimax-m2.7", name: "MiniMax M2.7", targetFormat: "claude", transportFormat: "claude" },
    { id: "minimax-m2.5", name: "MiniMax M2.5", targetFormat: "claude", transportFormat: "claude" },
    { id: "qwen3.8-max", name: "Qwen 3.8 Max", targetFormat: "claude", transportFormat: "claude" },
    { id: "qwen3.7-max", name: "Qwen 3.7 Max", targetFormat: "claude", transportFormat: "claude" },
    { id: "qwen3.7-plus", name: "Qwen 3.7 Plus", targetFormat: "claude", transportFormat: "claude" },
    { id: "qwen3.6-plus", name: "Qwen 3.6 Plus", targetFormat: "claude", transportFormat: "claude" },
  ],
};
