export default {
  id: "zed",
  alias: "zed",
  uiAlias: "zed",
  display: {
    name: "Zed Hosted Models",
    icon: "code_blocks",
    color: "#101010",
    textIcon: "ZD",
    website: "https://zed.dev",
    notice: {
      signupUrl: "https://zed.dev",
    },
  },
  category: "oauth",
  authType: "oauth",
  authModes: ["oauth"],
  transport: {
    baseUrl: "https://cloud.zed.dev/completions",
    llmBaseUrl: "https://cloud.zed.dev",
    cloudBaseUrl: "https://cloud.zed.dev",
    webBaseUrl: "https://zed.dev",
    format: "openai",
    forceStream: true,
    timeoutMs: 120000,
    stallTimeoutMs: 120000,
    appVersion: "0.200.0",
  },
  models: [],
  oauth: {
    webBaseUrl: "https://zed.dev",
    cloudBaseUrl: "https://cloud.zed.dev",
    llmBaseUrl: "https://cloud.zed.dev",
    nativeSignInUrl: "https://zed.dev/native_app_signin",
    userInfoUrl: "https://cloud.zed.dev/client/users/me",
    llmTokenUrl: "https://cloud.zed.dev/client/llm_tokens",
    modelsUrl: "https://cloud.zed.dev/models",
    completionsUrl: "https://cloud.zed.dev/completions",
    defaultNativeAppPort: 58443,
  },
};
