import { NextResponse } from "next/server";
import { generatePKCE } from "@/lib/oauth/utils/pkce";
import { KiroService } from "@/lib/oauth/services/kiro";
import { KIRO_EXTERNAL_IDP_DEFAULTS } from "@/lib/oauth/constants/oauth";
import { listActiveCaptures } from "../captureStore";

/**
 * POST /api/oauth/kiro/external-idp/authorize
 *
 * Starts an external IdP (Microsoft Entra ID) OAuth flow.
 *
 * Body (all required):
 *   - issuerUrl: tenant issuer URL, e.g. "https://login.microsoftonline.com/{tenant}/v2.0"
 *   - clientId:  Azure App Registration client id
 *   - scopes:    space-separated scope string (defaults to KIRO_EXTERNAL_IDP_DEFAULTS.scopes)
 *   - codeVerifier: PKCE verifier generated by the client (kept client-side only)
 *
 * Returns:
 *   - authUrl:        URL the user must be sent to in their browser
 *   - state:          CSRF state bound to the loopback capture session
 *   - redirectUri:    the loopback redirect URI (echoed back so the client can confirm)
 *   - portInUse:      true if the loopback port was already bound; user may need to close Kiro IDE
 */
export async function POST(request) {
  try {
    const body = await request.json().catch(() => ({}));
    const {
      issuerUrl,
      clientId,
      scopes,
      codeVerifier,
      authEndpoint,
      redirectUri,
    } = body || {};

    if (!issuerUrl || !clientId || !codeVerifier) {
      return NextResponse.json(
        { error: "issuerUrl, clientId, and codeVerifier are required" },
        { status: 400 }
      );
    }

    const kiroService = new KiroService();
    const { codeChallenge, state } = generatePKCE();

    // Probe whether the loopback port is free. If it isn't, we still issue
    // the authUrl so the user can complete the flow manually, but we flag
    // `portInUse` so the UI can warn them that the redirect won't auto-capture.
    let portInUse = false;
    try {
      const probe = kiroService.startLoopbackCapture({
        expectedState: state,
        timeoutMs: KIRO_EXTERNAL_IDP_DEFAULTS.loopbackTimeoutMs,
      });
      listActiveCaptures().set(state, probe);
      // Eagerly listen for EADDRINUSE so we can flag it before responding.
      probe.promise.catch(() => {
        // Errors are surfaced to the caller via the exchange route or
        // via a separate GET /status; nothing to do here.
      });
    } catch (err) {
      if (err && (err.code === "EADDRINUSE" || /EADDRINUSE/.test(String(err.message)))) {
        portInUse = true;
      } else {
        throw err;
      }
    }

    const authUrl = kiroService.buildExternalIdpAuthUrl({
      issuerUrl,
      clientId,
      scopes,
      codeChallenge,
      state,
      redirectUri,
      authEndpoint,
    });

    return NextResponse.json({
      authUrl,
      state,
      redirectUri: redirectUri || KIRO_EXTERNAL_IDP_DEFAULTS.redirectUri,
      portInUse,
    });
  } catch (error) {
    console.error("Kiro external-idp authorize error:", error.message);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

/**
 * GET /api/oauth/kiro/external-idp/authorize?state=...
 *
 * Polled by the UI to know whether the loopback server has captured the
 * authorization code yet. Returns:
 *   - status: "pending" | "captured" | "expired" | "error"
 *   - code, state when captured
 */
export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const state = searchParams.get("state");
  if (!state) {
    return NextResponse.json({ error: "state is required" }, { status: 400 });
  }

  const capture = listActiveCaptures().get(state);
  if (!capture) {
    return NextResponse.json({ status: "expired" });
  }

  // Race the capture against a short tick so we don't block the request thread.
  const tick = new Promise((resolve) => setTimeout(() => resolve("tick"), 250));
  const winner = await Promise.race([capture.promise.then(() => "captured").catch((err) => err), tick]);
  if (winner === "tick") {
    return NextResponse.json({ status: "pending" });
  }
  if (winner instanceof Error) {
    listActiveCaptures().delete(state);
    return NextResponse.json({ status: "error", error: winner.message }, { status: 400 });
  }
  // Captured — remove from store and return the code.
  listActiveCaptures().delete(state);
  return NextResponse.json({ status: "captured", code: winner.code, state: winner.state });
}