#!/usr/bin/env python3
"""
Rename video files to a clean standard format:
    Performer - Title (Resolution).mp4
Usage: python rename_videos.py [VIDEO_DIR] [--dry-run]
Default VIDEO_DIR: C:\\.000_AI\\.01_Vids
Expects catalog.json in the VIDEO_DIR (generated by catalog_videos.py).
"""

import json
import re
import sys
from pathlib import Path

DEFAULT_VIDEO_DIR = r"C:\.000_AI\.01_Vids"

def sanitize(name):
    name = re.sub(r'[<>"/\\|?*]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

def build_new_name(entry):
    performers = entry.get('performers', [])
    title = entry.get('title', '')
    resolution = entry.get('resolution', '')
    
    perf_str = ', '.join(performers) if performers else 'Unknown'
    
    res_map = {
        '4K (2160p)': '2160p',
        '2K (1440p)': '1440p',
        '1080p': '1080p',
        '720p': '720p',
        '4K': '2160p',
    }
    res_short = res_map.get(resolution, 'Unknown')
    
    new_name = f"{perf_str} - {title} ({res_short}).mp4"
    return sanitize(new_name)

def main():
    args = sys.argv[1:]
    dry_run = '--dry-run' in args
    video_dir = Path([a for a in args if not a.startswith('--')][0]) if [a for a in args if not a.startswith('--')] else Path(DEFAULT_VIDEO_DIR)
    
    catalog_file = video_dir / "catalog.json"
    if not catalog_file.exists():
        print(f"Catalog not found: {catalog_file}")
        print("Run catalog_videos.py first.")
        return
    
    with open(catalog_file, 'r', encoding='utf-8') as f:
        catalog = json.load(f)
    
    entries = catalog.get('entries', [])
    renamed = 0
    skipped = 0
    
    print("=" * 70)
    print("VIDEO RENAME" + (" (DRY RUN)" if dry_run else ""))
    print("=" * 70)
    
    for entry in entries:
        old_name = entry['filename']
        old_path = video_dir / old_name
        new_name = build_new_name(entry)
        new_path = video_dir / new_name
        
        if old_name == new_name:
            skipped += 1
            continue
        
        counter = 1
        original_new = new_path
        while new_path.exists() and new_path != old_path:
            stem = original_new.stem
            new_name = f"{stem}_{counter}.mp4"
            new_path = video_dir / new_name
            counter += 1
        
        print(f"  OLD: {old_name[:65]}")
        print(f"  NEW: {new_name[:65]}")
        print()
        
        if not dry_run:
            try:
                old_path.rename(new_path)
                renamed += 1
            except Exception as e:
                print(f"  ERROR: {e}")
                skipped += 1
        else:
            renamed += 1
    
    print("=" * 70)
    if dry_run:
        print(f"DRY RUN complete. {renamed} files would be renamed, {skipped} unchanged.")
        print("Run without --dry-run to execute.")
    else:
        print(f"Done. {renamed} files renamed, {skipped} unchanged.")
    print("=" * 70)

if __name__ == '__main__':
    main()
