import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const REQUIRED=['deployJournal','gitState','liveState','pm2State','warpState','strictProxyState','guardState','logState'];
const ALLOWED={deployJournal:['status','state','startedAt'],gitState:['status','expectedCommit','upstream'],liveState:['status','liveCommit','version'],pm2State:['status','processStatus','unstableRestarts'],warpState:['status','listening','warp'],strictProxyState:['status','total','strict','drift'],guardState:['status','httpStatus'],logState:['status','findings'],canary:['status','httpStatus','model']};
const clean=(name,value)=>Object.fromEntries(ALLOWED[name].filter(k=>value?.[k]!==undefined).map(k=>[k,value[k]]));
export function classifyExit(gates){const values=Array.isArray(gates)?gates:Object.values(gates);return values.some(x=>x.status==='error')?2:values.some(x=>x.status==='fail')?1:0;}
export async function runVerification(options={},adapter){const gates={};for(const name of REQUIRED){try{gates[name]=clean(name,await adapter[name]());}catch{gates[name]={status:'error',reason:'check_failed'};}}if(options.canary){try{gates.canary=clean('canary',await adapter.canaryState({model:options.canaryModel}));}catch{gates.canary={status:'error',reason:'check_failed'};}}else gates.canary={status:'not_run'};const exitCode=classifyExit(gates);const summary=structuredClone(gates);return {exitCode,overall:exitCode===0?'pass':exitCode===1?'fail':'error',gates,summary};}
export async function writeReport(result,{reportDir,checkpoint,now=new Date()}){if(!/^[A-Za-z0-9+._-]+$/.test(checkpoint||''))throw new Error('invalid_checkpoint');const root=path.resolve(reportDir);await mkdir(root,{recursive:true,mode:0o700});const stamp=now.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const file=path.resolve(root,`${stamp}-${checkpoint}.json`);if(path.dirname(file)!==root)throw new Error('invalid_path');const report={timestamp:now.toISOString(),checkpoint,overall:result.overall,exitCode:result.exitCode,gates:result.summary};await writeFile(file,`${JSON.stringify(report,null,2)}\n`,{flag:'wx',mode:0o600});return file;}
