"use client";

import React, { useState } from "react";
import { 
  Plus, 
  Cpu, 
  Activity, 
  Info, 
  DollarSign,
  ChevronRight,
  Zap,
  LayoutGrid
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { 
  Card, 
  CardContent, 
  CardHeader, 
  CardTitle, 
  CardFooter 
} from "@/components/ui/card";
import PricingModal from "@/shared/components/PricingModal";

interface PricingData {
  [provider: string]: {
    [model: string]: any;
  };
}

interface PricingPageClientProps {
  initialPricing: PricingData;
}

export default function PricingPageClient({ initialPricing }: PricingPageClientProps) {
  const [showModal, setShowModal] = useState(false);
  const [currentPricing, setCurrentPricing] = useState<PricingData>(initialPricing || {});
  const [loading, setLoading] = useState(false);

  const loadPricing = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/pricing");
      if (res.ok) setCurrentPricing(await res.json());
    } catch (e) { console.error(e); } finally { setLoading(false); }
  };

  const getModelCount = () => {
    if (!currentPricing) return 0;
    return Object.values(currentPricing).reduce((acc, p) => acc + Object.keys(p).length, 0);
  };

  return (
    <div className="mx-auto max-w-5xl flex flex-col gap-8 py-8 px-4">
      {/* Header */}
      <header className="flex flex-col md:flex-row md:items-end justify-between gap-6 pb-8 border-b border-border/50">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-muted-foreground font-bold text-[10px] uppercase tracking-widest">
            <DollarSign className="size-4" />
            Financial Configuration
          </div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground uppercase">Rate Controller</h1>
          <p className="text-sm text-muted-foreground font-medium italic opacity-70">
            Fine-tune infrastructure cost metrics for real-time traffic analysis.
          </p>
        </div>

        <Button size="sm" className="font-bold text-[10px] uppercase tracking-widest h-9 px-6 rounded-none shadow-none" onClick={() => setShowModal(true)}>
          <Plus className="size-3.5 mr-2" /> Adjust Rates
        </Button>
      </header>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <StatCard label="Model catalog" value={loading ? "..." : getModelCount()} icon={Cpu} />
        <StatCard label="Active hubs" value={loading ? "..." : Object.keys(currentPricing || {}).length} icon={LayoutGrid} />
        <StatCard label="System health" value="Active" icon={Zap} color="text-emerald-500" />
      </div>

      <div className="grid gap-6 lg:grid-cols-12">
        {/* Help Card */}
        <Card className="lg:col-span-7 shadow-none border-border/50 bg-muted/5 overflow-hidden rounded-none">
          <CardHeader className="border-b border-border/40 bg-muted/20">
             <CardTitle className="text-[10px] font-bold uppercase tracking-widest flex items-center gap-2">
                <Info className="size-4 text-primary" />
                Calculation Logic
             </CardTitle>
          </CardHeader>
          <CardContent className="p-6 space-y-4 text-xs font-medium leading-relaxed text-muted-foreground/80 italic">
            <div className="p-4 rounded-none border border-border/50 bg-background space-y-2 shadow-inner">
               <p className="font-bold text-foreground not-italic">Economic Formula</p>
               <code className="block p-2 bg-muted rounded-none font-mono text-[10px] text-primary">Cost = (Input × Rate) + (Output × Rate) + (Cache × Discount)</code>
            </div>
            <p>Rates are defined as <span className="font-bold text-foreground not-italic">USD per 1,000,000 tokens</span>. For example, a rate of 2.50 represents $2.50 per 1M units.</p>
            <div className="grid grid-cols-2 gap-4 pt-2">
               <div className="space-y-1">
                  <p className="font-bold text-foreground text-[10px] uppercase tracking-wider not-italic">Input Layer</p>
                  <p>Standard prompt tokens sent to the inference engine.</p>
               </div>
               <div className="space-y-1">
                  <p className="font-bold text-foreground text-[10px] uppercase tracking-wider not-italic">Output Layer</p>
                  <p>Completion and reasoning tokens generated by the model.</p>
               </div>
            </div>
          </CardContent>
        </Card>

        {/* Preview Card */}
        <Card className="lg:col-span-5 shadow-none border-border/50 overflow-hidden flex flex-col rounded-none bg-background/50">
           <CardHeader className="border-b border-border/40 bg-muted/20">
              <CardTitle className="text-[10px] font-bold uppercase tracking-widest flex items-center gap-2">
                 <Activity className="size-4 text-primary" />
                 Rate Snapshot
              </CardTitle>
           </CardHeader>
           <CardContent className="p-0 flex-1 overflow-y-auto no-scrollbar max-h-[300px]">
              {loading ? <div className="p-10 text-center opacity-20"><Activity className="size-6 animate-spin mx-auto" /></div> : currentPricing ? (
                <div className="divide-y divide-border/30">
                   {Object.keys(currentPricing).slice(0, 10).map(p => (
                      <div key={p} className="p-3.5 hover:bg-muted/30 transition-all flex items-center justify-between group">
                         <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60 group-hover:text-primary transition-colors">{p}</span>
                         <Badge variant="outline" className="h-4 text-[9px] font-bold border-border/40 bg-muted/40 px-1.5 rounded-none tabular-nums opacity-60">{Object.keys(currentPricing[p]).length} MODELS</Badge>                      </div>
                   ))}
                </div>
              ) : <div className="p-10 text-center opacity-20 text-[10px] font-bold uppercase tracking-widest">No data found</div>}
           </CardContent>
           <CardFooter className="p-2 border-t border-border/40 bg-muted/10 shrink-0">
              <Button variant="ghost" size="sm" className="w-full h-8 text-[10px] font-bold uppercase tracking-widest group rounded-none" onClick={() => setShowModal(true)}>
                 View full registry <ChevronRight className="ml-1 size-3 group-hover:translate-x-1 transition-transform" />
              </Button>
           </CardFooter>
        </Card>
      </div>

      {showModal && <PricingModal isOpen={showModal} onClose={() => setShowModal(false)} onSave={loadPricing} />}
    </div>
  );
}

interface StatCardProps {
  label: string;
  value: string | number;
  icon: any;
  color?: string;
}

function StatCard({ label, value, icon: Icon, color }: StatCardProps) {
  return (
    <Card className="shadow-none border-border/50 bg-muted/10 rounded-none hover:bg-muted/20 transition-colors">
      <CardContent className="p-4 flex items-center justify-between">
        <div className="space-y-0.5">
           <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground opacity-60">{label}</p>
           <p className="text-2xl font-bold tracking-tight tabular-nums text-foreground">{value}</p>
        </div>
        <div className={cn("p-2 rounded-none bg-background border border-border/50 shadow-none", color)}>
           <Icon className="size-4" />
        </div>
      </CardContent>
    </Card>
  );
}
